// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import Header from "@/components/Header";
import { ClerkLoaded, ClerkProvider } from "@clerk/nextjs";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkLoaded>
            <div className="flex flex-col flex-1 h-screen">
                <Header />
                <main className="flex-1 overflow-y-auto">
                    {children}
                </main>
            </div>
        </ClerkLoaded>
    )
}
